apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smartfactory-dss
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - configmaps.yaml
  - resource-governance.yaml
  - pvcs.yaml
  - services.yaml
  - statefulsets.yaml
  - deployments.yaml
  - pod-disruption-budgets.yaml
  - networkpolicies.yaml
  - ingress.yaml
configMapGenerator:
  - name: mysql-shared-config
    files:
      - files/zz-smartfactory.cnf
generatorOptions:
  disableNameSuffixHash: true
commonLabels:
  app.kubernetes.io/part-of: smartfactory-dss
