apiVersion: v1
kind: Namespace
metadata:
  name: smartfactory-dss
  labels:
    app.kubernetes.io/name: smartfactory-dss
    app.kubernetes.io/part-of: smartfactory-dss
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
