apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: laravel-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: laravel-app
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fastapi-ai
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fastapi-ai
