apiVersion: v1
kind: ServiceAccount
metadata:
  name: laravel-app
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi-ai
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sage-erp-simulator
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-dss
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-erp
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
automountServiceAccountToken: false
