apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smartfactory-dss
resources:
  - serviceaccounts-rbac.yaml
  - persistent-volumes.yaml
  - services.yaml
  - workloads.yaml
  - networkpolicies.yaml
configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=files/prometheus.yml
      - alerts.yml=files/alerts.yml
  - name: blackbox-config
    files:
      - blackbox.yml=files/blackbox.yml
  - name: grafana-provisioning
    files:
      - datasource.yml=files/grafana-datasource.yml
      - dashboard-provider.yml=files/grafana-dashboard-provider.yml
  - name: grafana-dashboards
    files:
      - smartfactory-overview.json=files/smartfactory-overview.json
      - smartfactory-application-observability.json=files/smartfactory-application-observability.json
generatorOptions:
  labels:
    app.kubernetes.io/part-of: smartfactory-dss
    app.kubernetes.io/component: monitoring
commonLabels:
  app.kubernetes.io/part-of: smartfactory-dss
  app.kubernetes.io/managed-by: kustomize
