<?php

namespace App\Services\AI\Reports;

use App\DTOs\AI\Reports\AiInferenceReport;

final class AiInferenceReportTableBuilder
{
    public const VERIFIED_FACT = 'verified_fact';

    public const GUARDED_AI_METADATA = 'guarded_ai_metadata';

    public const GUARDED_AI_NARRATIVE = 'guarded_ai_narrative';

    /**
     * @return list<array{
     *     content_type:string,
     *     section:string,
     *     metric:string,
     *     value:string|int|float
     * }>
     */
    public function rows(AiInferenceReport $report): array
    {
        $rows = [
            $this->row(
                self::VERIFIED_FACT,
                'Report',
                'Title',
                $report->title(),
            ),
            $this->row(
                self::VERIFIED_FACT,
                'Report',
                'Generated at UTC',
                $report->generatedAt->utc()->toIso8601String(),
            ),
            $this->row(
                self::VERIFIED_FACT,
                'Report',
                'Generated by',
                $report->generatedByName,
            ),
            $this->row(
                self::VERIFIED_FACT,
                'Report',
                'Operation',
                $report->operation,
            ),
            $this->row(
                self::VERIFIED_FACT,
                'Report',
                'Task',
                $report->task(),
            ),
            $this->row(
                self::VERIFIED_FACT,
                'Report',
                'Inference request ID',
                $report->requestId,
            ),
            $this->row(
                self::VERIFIED_FACT,
                'Report',
                'Data classification',
                'simulated_prototype',
            ),
            $this->row(
                self::VERIFIED_FACT,
                'Report',
                'Content boundary',
                'Verified numeric facts and model metadata remain authoritative. '
                    .'Any guarded AI narrative is exported separately and cannot '
                    .'change these values.',
            ),
        ];

        foreach ($report->context as $key => $value) {
            $rows[] = $this->row(
                self::VERIFIED_FACT,
                'Input context',
                $this->label((string) $key),
                $this->scalar($value),
            );
        }

        foreach ($this->flatten($report->result) as $key => $value) {
            $rows[] = $this->row(
                self::VERIFIED_FACT,
                str_starts_with($key, 'metadata.')
                    ? 'Model metadata'
                    : 'Inference result',
                $this->label($key),
                $value,
            );
        }

        if ($report->metrics === null) {
            $rows[] = $this->row(
                self::VERIFIED_FACT,
                'Model evaluation',
                'Metrics status',
                'Unavailable when the inference result was captured',
            );
        } else {
            $metricPayload = $report->metrics['metrics'] ?? [];
            foreach ($this->flatten($metricPayload) as $key => $value) {
                $rows[] = $this->row(
                    self::VERIFIED_FACT,
                    'Model evaluation',
                    $this->label($key),
                    $value,
                );
            }

            $derivations = $report->metrics['metric_derivations'] ?? [];
            if (is_array($derivations)) {
                foreach ($this->flatten($derivations) as $key => $value) {
                    $rows[] = $this->row(
                        self::VERIFIED_FACT,
                        'Metric derivations',
                        $this->label($key),
                        $value,
                    );
                }
            }
        }

        $limitations = $report->result['metadata']['limitations'] ?? [];
        if (is_array($limitations)) {
            foreach (array_values($limitations) as $index => $limitation) {
                $rows[] = $this->row(
                    self::VERIFIED_FACT,
                    'Model limitations',
                    'Limitation '.($index + 1),
                    $this->scalar($limitation),
                );
            }
        }

        if ($report->explanation !== null) {
            $explanation = $report->explanation;
            $metadata = [
                'Contract name' => $explanation::CONTRACT_NAME,
                'Contract version' => $explanation::CONTRACT_VERSION,
                'Explanation ID' => $explanation->explanationId,
                'Explanation type' => $explanation->explanationType,
                'Role' => $explanation->role,
                'Language' => $explanation->language,
                'Explanation request ID' => $explanation->requestId,
                'Linked inference request ID' => $explanation->inferenceRequestId,
                'Attached at UTC' => $explanation->attachedAt
                    ->utc()
                    ->toIso8601String(),
                'Data classification' => $explanation::DATA_CLASSIFICATION,
            ];

            foreach ($metadata as $metric => $value) {
                $rows[] = $this->row(
                    self::GUARDED_AI_METADATA,
                    'Explanation metadata',
                    $metric,
                    $value,
                );
            }

            $rows[] = $this->row(
                self::GUARDED_AI_NARRATIVE,
                'Explanation summary',
                'Summary',
                $explanation->narrative['summary'],
            );

            foreach (
                $explanation->narrative['observations']
                as $index => $observation
            ) {
                $rows[] = $this->row(
                    self::GUARDED_AI_NARRATIVE,
                    'Explanation observations',
                    'Observation '.($index + 1),
                    $observation,
                );
            }

            foreach (
                $explanation->narrative['suggested_human_checks']
                as $index => $check
            ) {
                $rows[] = $this->row(
                    self::GUARDED_AI_NARRATIVE,
                    'Suggested human checks',
                    'Check '.($index + 1),
                    $check,
                );
            }

            foreach (
                $explanation->narrative['limitations']
                as $index => $limitation
            ) {
                $rows[] = $this->row(
                    self::GUARDED_AI_NARRATIVE,
                    'Explanation limitations',
                    'Limitation '.($index + 1),
                    $limitation,
                );
            }

            foreach (
                $explanation->narrative['referenced_fact_keys']
                as $index => $factKey
            ) {
                $rows[] = $this->row(
                    self::GUARDED_AI_METADATA,
                    'Explanation grounding',
                    'Referenced fact '.($index + 1),
                    $factKey,
                );
            }
        }

        return $rows;
    }

    /**
     * @return array{
     *     content_type:string,
     *     section:string,
     *     metric:string,
     *     value:string|int|float
     * }
     */
    private function row(
        string $contentType,
        string $section,
        string $metric,
        string|int|float $value,
    ): array {
        return [
            'content_type' => $contentType,
            'section' => $section,
            'metric' => $metric,
            'value' => $value,
        ];
    }

    /**
     * @return array<string, string|int|float>
     */
    private function flatten(mixed $value, string $prefix = ''): array
    {
        if (! is_array($value)) {
            return $prefix === ''
                ? []
                : [$prefix => $this->scalar($value)];
        }

        $output = [];
        foreach ($value as $key => $item) {
            $path = $prefix === ''
                ? (string) $key
                : $prefix.'.'.$key;

            if (is_array($item)) {
                $output += $this->flatten($item, $path);
            } else {
                $output[$path] = $this->scalar($item);
            }
        }

        return $output;
    }

    private function scalar(mixed $value): string|int|float
    {
        if (is_int($value) || is_float($value)) {
            return $value;
        }

        if (is_bool($value)) {
            return $value ? 'Yes' : 'No';
        }

        if ($value === null) {
            return 'N/A';
        }

        return (string) $value;
    }

    private function label(string $value): string
    {
        return ucwords(
            str_replace(
                ['_', '.'],
                [' ', ' / '],
                $value,
            ),
        );
    }
}
