<?php

namespace App\Services\Reports;

use App\DTOs\Analytics\ProductionKpiUnitSummary;
use App\DTOs\Analytics\ProductionMetricRow;
use App\DTOs\Reports\ProductionReport;

final class ProductionReportTableBuilder
{
    /**
     * @return list<list<string|int|float>>
     */
    public function rows(
        ProductionReport $report
    ): array {
        $rows = [
            [
                'SmartFactory DSS production report',
            ],
            [
                'Report title',
                $report->title,
            ],
            [
                'Report type',
                $report->type->label(),
            ],
            [
                'Generated at',
                $report->generatedAt
                    ->setTimezone(
                        $report->filter->timezone
                    )
                    ->format('Y-m-d H:i:s T'),
            ],
            [
                'Generated by',
                $report->generatedByName,
            ],
            [
                'Generating account',
                $report->generatedByEmail,
            ],
            [],
            [
                'Applied filters',
            ],
        ];

        foreach (
            $report->appliedFilters
            as $label => $value
        ) {
            $rows[] = [
                $label,
                $value,
            ];
        }

        $rows[] = [];
        $rows[] = [
            'Production KPI summary',
        ];
        $rows[] = [
            'Quantity unit',
            'Target orders',
            'Records',
            'Validated',
            'Provisional',
            'Target quantity',
            'Actual quantity',
            'Good quantity',
            'Rejected quantity',
            'Achievement %',
            'Rejection %',
            'Runtime minutes',
            'Downtime minutes',
        ];

        foreach (
            $report->summary->units
            as $unit
        ) {
            $rows[] = $this->unitRow($unit);
        }

        if ($report->summary->units === []) {
            $rows[] = [
                'No matching production data',
            ];
        }

        $rows[] = [];
        $rows[] = [
            'Primary breakdown',
            $report->primaryDimensionLabel(),
        ];
        $rows[] = [
            $report->primaryDimensionLabel(),
            'Quantity unit',
            'Target count',
            'Record count',
            'Validated',
            'Provisional',
            'Target quantity',
            'Actual quantity',
            'Good quantity',
            'Rejected quantity',
            'Achievement %',
            'Rejection %',
            'Runtime minutes',
            'Downtime minutes',
        ];

        foreach (
            $report->primaryRows()
            as $metric
        ) {
            $rows[] = $this->metricRow(
                $metric
            );
        }

        if ($report->primaryRows() === []) {
            $rows[] = [
                'No matching breakdown data',
            ];
        }

        $rows[] = [];
        $rows[] = [
            'Data basis',
            $report->dataBasisLabel(),
        ];

        return $rows;
    }

    /**
     * @return list<string|int|float>
     */
    private function unitRow(
        ProductionKpiUnitSummary $unit
    ): array {
        return [
            $unit->quantityUnit,
            $unit->targetOrderCount,
            $unit->recordCount,
            $unit->validatedRecordCount,
            $unit->provisionalRecordCount,
            (float) $unit->targetQuantity,
            (float) $unit->actualQuantity,
            (float) $unit->goodQuantity,
            (float) $unit->rejectedQuantity,
            $unit->achievementPercentage ?? '',
            $unit->rejectionPercentage ?? '',
            $unit->runtimeMinutes,
            $unit->downtimeMinutes,
        ];
    }

    /**
     * @return list<string|int|float>
     */
    private function metricRow(
        ProductionMetricRow $metric
    ): array {
        return [
            $metric->label,
            $metric->quantityUnit,
            $metric->targetCount,
            $metric->recordCount,
            $metric->validatedRecordCount,
            $metric->provisionalRecordCount,
            (float) $metric->targetQuantity,
            (float) $metric->actualQuantity,
            (float) $metric->goodQuantity,
            (float) $metric->rejectedQuantity,
            $metric->achievementPercentage ?? '',
            $metric->rejectionPercentage ?? '',
            $metric->runtimeMinutes,
            $metric->downtimeMinutes,
        ];
    }
}
