@extends('layouts.auth')

@section('title', 'Two-factor authentication')

@section('content')
    <div
        x-data="{ recoveryMode: false }"
    >
        <div class="mb-4">
            <p
                class="text-uppercase small fw-semibold
                       text-secondary mb-2"
            >
                Two-factor authentication
            </p>

            <h2 class="h3 fw-bold mb-2">
                Verify your secure sign-in
            </h2>

            <p
                class="text-muted-smartfactory mb-0"
                x-show="! recoveryMode"
            >
                Enter the six-digit code generated by your
                authenticator application.
            </p>

            <p
                class="text-muted-smartfactory mb-0"
                x-show="recoveryMode"
                x-cloak
            >
                Enter one unused recovery code.
            </p>
        </div>

        <form
            method="POST"
            action="{{ route('two-factor.login.store') }}"
            novalidate
        >
            @csrf

            <div
                class="mb-4"
                x-show="! recoveryMode"
            >
                <label
                    for="code"
                    class="form-label fw-semibold"
                >
                    Authentication code
                </label>

                <input
                    type="text"
                    id="code"
                    name="code"
                    class="form-control"
                    autocomplete="one-time-code"
                    inputmode="numeric"
                    pattern="[0-9]*"
                    maxlength="6"
                    x-bind:disabled="recoveryMode"
                    autofocus
                >
            </div>

            <div
                class="mb-4"
                x-show="recoveryMode"
                x-cloak
            >
                <label
                    for="recovery_code"
                    class="form-label fw-semibold"
                >
                    Recovery code
                </label>

                <input
                    type="text"
                    id="recovery_code"
                    name="recovery_code"
                    class="form-control font-monospace"
                    autocomplete="one-time-code"
                    maxlength="100"
                    x-bind:disabled="! recoveryMode"
                >
            </div>

            <button
                type="submit"
                class="btn btn-smartfactory w-100"
            >
                Verify and sign in
            </button>
        </form>

        <div class="text-center mt-4">
            <button
                type="button"
                class="btn btn-link text-decoration-none"
                x-on:click="recoveryMode = ! recoveryMode"
            >
                <span
                    x-text="
                        recoveryMode
                            ? 'Use an authenticator code'
                            : 'Use a recovery code'
                    "
                ></span>
            </button>
        </div>

        <div class="security-note rounded-3 p-3 mt-3 small">
            Each recovery code can be used only once.
        </div>
    </div>
@endsection